"""Add user_feedback_score_indexes

Revision ID: ce89b0147ed4
Revises: fe7527dab092
Create Date: 2024-06-06 14:02:42.952902

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce89b0147ed4"
down_revision: str | None = "fe7527dab092"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_user_feedback_scores_thread_id"), "user_feedback_scores", ["thread_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_feedback_scores_thread_id"), table_name="user_feedback_scores")
    # ### end Alembic commands ###
