"""Add Users table

Revision ID: 820f66a7f6b8
Revises: ce89b0147ed4
Create Date: 2024-06-12 17:48:55.711882

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "820f66a7f6b8"
down_revision: str | None = "ce89b0147ed4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slack_user_id", sa.String(), nullable=False),
        sa.Column("confluence_access_token", sa.String(), nullable=True),
        sa.Column("confluence_access_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confluence_refresh_token", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slack_user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
