"""Add Auth Message ID

Revision ID: e3c0780adab9
Revises: 01987d7a151b
Create Date: 2024-06-14 17:02:29.342234

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3c0780adab9"
down_revision: str | None = "01987d7a151b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("auth_message_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auth_message_id")
    # ### end Alembic commands ###
