"""Add User Feedback Score

Revision ID: dc70c5e7f152
Revises: 0cb90fcc57c7
Create Date: 2024-05-17 15:29:20.116670

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc70c5e7f152"
down_revision: str | None = "0cb90fcc57c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_feedback_scores",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("slack_user_id", sa.String(), nullable=False),
        sa.Column("channel_id", sa.String(), nullable=False),
        sa.Column("thread_id", sa.String(length=17), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("score >= 1 AND score <= 5", name="check_user_feedback_score_value"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("user_feedback_score")
