global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'chat_bot'
    static_configs:
      - targets: ['dev_chat_bot:9090']

  - job_name: 'dev_web'
    static_configs:
      - targets: ['dev_web:9090']

  - job_name: 'dev_menu'
    static_configs:
      - targets: ['dev_menu:9090']

  - job_name: 'weaviate'
    static_configs:
      - targets: ['weaviate:9090']
